{{ $ca := genCA "svc-cat-ca" 3650 }}
{{ $svcName := include "kube-service-annotate.fullname" . }}
{{ $cn := printf "%s.%s.svc" $svcName .Release.Namespace }}
{{ $altName1 := printf "%s.cluster.local" $cn }}
{{ $altName2 := printf "%s" $cn }}
{{ $server := genSignedCert $cn nil (list $altName1 $altName2) 365 $ca }}

apiVersion: v1
kind: List
metadata:
items:

- apiVersion: v1
  kind: Secret
  metadata:
    name: {{ template "kube-service-annotate.fullname" . }}
  data:
    tls.crt: {{ b64enc $server.Cert }}
    tls.key: {{ b64enc $server.Key }}
    ca.crt:  {{ b64enc $ca.Cert }}

- apiVersion: admissionregistration.k8s.io/v1beta1
  kind: MutatingWebhookConfiguration
  metadata:
    name: {{ template "kube-service-annotate.fullname" . }}
  webhooks:
  - name: pods.{{ template "kube-service-annotate.name" . }}.admission.banzaicloud.com
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "kube-service-annotate.fullname" . }}
        path: /pods
      caBundle: {{ b64enc $ca.Cert }}
    rules:
      - operations:
          - CREATE
        apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - services
    failurePolicy: {{ .Values.podsFailurePolicy }}
    namespaceSelector:
    {{- if .Values.namespaceSelector.matchLabels }}
      matchLabels:
{{ toYaml .Values.namespaceSelector.matchLabels | indent 8 }}
      {{- end }}
      matchExpressions:
      {{- if .Values.namespaceSelector.matchExpressions }}
{{ toYaml .Values.namespaceSelector.matchExpressions | indent 6 }}
      {{- end }}
    sideEffects: NoneOnDryRun