apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-service-annotate.fullname"  . }}
  labels:
{{ include "kube-service-annotate.labels" . | indent 4 }}
data:
  rules.yaml: |
{{ toYaml .Values.rules | indent 4 }}