apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-service-annotate.fullname" . }}
  labels:
{{ include "kube-service-annotate.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-service-annotate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kube-service-annotate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KSA_RULES_FILE
              value: "/config/rules.yaml"
            - name: KSA_TLS_CERT_FILE
              value: "/tls/tls.crt"
            - name: KSA_TLS_KEY_FILE
              value: "/tls/tls.key"
            - name: KSA_DEBUG
              value: "{{ .Values.debug | default false}}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: tls-volume
              mountPath: /tls
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "kube-service-annotate.fullname" . }}
        - name: tls-volume
          secret:
            secretName: {{ include "kube-service-annotate.fullname" . }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
